const fs=require('fs');
const nav=[['introduce','PROM RECORD'],['article','기사'],['image','이미지'],['video','영상'],['final','Final project']];
const titles={article:'Articles',image:'Images',video:'Motion',final:'Final project'};
function shell(page,body){return `<!doctype html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="한국경제 AI 교육에서 만든 기사, 이미지, 영상, 최종 프로젝트를 모은 개인 포트폴리오입니다."><title>${nav.find(x=>x[0]===page)[1]} · 한국경제 AI Archive</title><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="responsive.css"><script src="app.js" defer></script></head><body class="${page}-page"><header><a class="brand" href="article.html" aria-label="한국경제 AI 포트폴리오 홈"><i class="brand-mark" aria-hidden="true"></i><span>한국경제 AI<small>CREATIVE ARCHIVE</small></span></a><nav aria-label="주 메뉴">${nav.map(([p,t])=>`<a href="${p}.html" ${p===page?'class="active" aria-current="page"':''}>${t}</a>`).join('')}</nav><span class="edition">LEARNING JOURNAL / 2026</span></header><main>${body}</main><footer><span>한국경제 AI 교육 · 개인 학습 포트폴리오</span><span>© 2026 Creative Archive. &nbsp; Made with curiosity.</span></footer><dialog aria-label="작품 상세"><button class="close" aria-label="닫기">×</button><div class="dialog-content"></div></dialog></body></html>`}
function heading(n,title,colored,intro){return `<div class="eyebrow"><span class="dot"></span> MY CREATIVE JOURNEY <span style="margin-left:auto;color:#89928b">0${n} / 04</span></div><div class="hero-heading"><h1>${title}<span>${colored}</span></h1><p class="intro">${intro}</p></div>`}
const article=heading(1,'Ideas into','<br>stories.','질문에서 시작해, 나만의 이야기로.<br>AI와 함께 읽고 탐구하며 기록한 기사입니다.')+`<div class="hero-meta"><span class="pill">ARTICLE COLLECTION</span><span class="subtle">생각을 담은 네 편의 기록 &nbsp;↙</span></div><section class="feature"><div class="feature-visual"><img class="art" src="assets/article-featured.png" alt="하늘색 배경의 딸기 케이크와 핑크 블러셔 제품"><span class="floating-label">FEATURED STORY</span></div><div class="feature-copy"><span class="kicker">01 &nbsp; INSIGHT / 생성형 AI</span><h2>AI시대, 아주 편리다</h2><p>일상의 번거로운 일부터 콘텐츠 제작까지.<br>AI가 만드는 편리함과, 그 안에서 필요한<br>우리의 판단과 창의성을 이야기합니다.</p><a class="read" href="#story-1" data-story="story-1">기사 읽기 <b>↗</b></a><span class="subtle" style="margin-top:23px">2026.09.10 &nbsp; · &nbsp; 학습 에세이</span></div></section><div class="section-top"><h2>Latest stories <sup>04</sup></h2><span class="subtle">배움의 순간을 한 편씩</span></div><div class="article-list">${[['02','이미지 한 장에도 기획이 필요하다','제작 노트 · 이미지 기획','story-2'],['03','30초 영상, 이야기를 설계하는 법','실습 기록 · 스토리보드','story-3'],['04','AI가 만든 결과물, 나의 관점으로 다듬기','생각의 기록 · 편집과 검토','story-4']].map(([num,title,cat,id])=>`<a class="article-row" href="#${id}" data-story="${id}"><span class="num">${num}</span><div><h3>${title}</h3><p>${cat} &nbsp; · &nbsp; 샘플</p></div><span class="subtle">2026.09.10</span><span class="row-arrow">↗</span></a>`).join('')}</div><div class="bottom-note"><p>작은 질문이, 다음 작업의 시작이 되도록.</p><a href="image.html">이미지 작업 보러 가기 &nbsp; ↗</a></div>`+
[["story-1","AI시대, 아주 편리다","인공지능은 일상 속 번거로운 일을 덜어 주는 도구다. 긴 글에서 핵심을 정리하고, 낯선 표현을 풀어 설명하며, 막막한 글쓰기의 첫 문장을 제안한다. 무엇부터 시작해야 할지 몰라 멈춰 있던 순간에도 AI와 대화하면 생각을 정리할 실마리를 얻을 수 있다. 콘텐츠 제작에서도 활용 방법은 다양하다. 기사 주제를 정한 뒤 구성안을 만들고, 이미지에 담을 장면을 구체화하거나 영상의 흐름을 설계하는 데 도움을 받을 수 있다. 반복 작업에 쓰던 시간을 줄이면 기획과 표현을 고민할 여유가 생긴다. 다만 편리하다고 모든 답이 정확한 것은 아니다. AI가 제시한 정보는 출처를 확인하고, 어색한 문장과 의도에 맞지 않는 결과는 직접 고쳐야 한다. 원하는 대상과 목적, 조건을 분명하게 전달하는 태도도 중요하다. AI 시대의 편리함은 버튼 한 번으로 완성되는 결과보다, 도구와 함께 생각을 발전시키는 과정에 있다. 기술에 판단을 맡기기보다 나의 관점을 더할 때 AI는 배움과 창작을 돕는 든든한 파트너가 된다."],['story-2','이미지 한 장에도 기획이 필요하다','이번 이미지 실습의 키워드는 “새로운 시작”이었다. 원하는 느낌을 막연하게 설명하는 대신 주제, 오브젝트, 색, 빛의 방향을 작은 기획 메모로 정리했다.','파란 조형물은 유연한 사고를, 투명한 구체는 질문을 상징하도록 설정했다. 결과물을 비교할 때는 화려함보다 의도한 메시지가 전달되는지를 기준으로 삼았다.','다음에는 같은 주제를 다른 구도와 재질로 표현해 볼 예정이다.'],['story-3','30초 영상, 이야기를 설계하는 법','짧은 영상일수록 한 번에 너무 많은 이야기를 담지 않기로 했다. 시작, 변화, 마무리의 세 장면으로 스토리보드를 나누었다.','카메라가 고정된 첫 장면에서 시작해 피사체의 작은 움직임으로 변화를 보여 주고, 마지막 장면에는 여백을 남겼다. 움직임을 제한하니 장면의 목적이 더 또렷해졌다.','실제 영상 제작 전 각 장면의 길이와 전환 시점을 다시 점검할 계획이다.'],['story-4','AI가 만든 결과물, 나의 관점으로 다듬기','첫 번째 결과물을 완성본으로 받아들이지 않는 연습을 했다. 문장에서는 모호한 표현을, 이미지에서는 주제와 관계없는 요소를 찾아 지웠다.','기사의 사실관계는 출처와 함께 확인하고, 근거가 없는 주장은 삭제하거나 질문으로 바꾸었다. 내 경험과 판단이 들어갈 부분도 별도로 표시했다.','AI와 작업할 때도 최종 선택의 기준은 내가 전하고 싶은 메시지다.']].map(([id,title,...paras])=>`<article class="story" id="${id}"><span class="kicker">LEARNING NOTES / 2026.09.10</span><h2>${title}</h2>${id==='story-1'?'':'<p class="sample-note">페이지 구성을 위한 임시 학습 에세이입니다. 실제 교육 기록이나 보도 기사가 아닙니다.</p>'}${paras.map(p=>`<p>${p}</p>`).join('')}</article>`).join('');
const works=[['blue-sculpture','01 / FORM & COLOR','Blue possibilities','형태를 비틀고, 생각을 넓히다.','코발트 블루 조형물과 투명한 구체로 표현한 창의적 가능성.','파란 조형물, 유리 구체, 라임 컬러, 부드러운 스튜디오 조명'],['green-glasshouse','02 / IMAGINARY SPACE','A greener tomorrow','상상 속에서 먼저 만나는 내일.','투명한 유리 온실과 초록의 식물이 공존하는 작은 미래 공간.','유리 온실, 라임빛 식물, 자연광, 미래의 정원'],['pink-dune','03 / LIGHT & TEXTURE','Soft horizon','가벼운 움직임이 남기는 잔상.','고요한 사구 위, 빛을 머금은 천의 질감을 탐구한 이미지.','분홍빛 반투명 천, 모래 언덕, 부드러운 빛, 초현실적 풍경']];
const images=heading(2,'Make room<br>for ','imagination.','머릿속 장면이 이미지가 되는 순간.<br>색과 형태, 빛으로 실험한 비주얼을 모았습니다.')+`<div class="hero-meta"><span class="pill">VISUAL EXPERIMENTS</span><span class="subtle">AI 생성 샘플 3작품 · 이미지를 누르면 크게 볼 수 있습니다</span></div><div class="gallery">${works.map(([file,cat,title,lead,desc,prompt])=>`<figure class="work"><button data-art="assets/${file}.png" data-title="${title}" aria-label="${title} 이미지 확대"><img class="art" src="assets/${file}.png" alt="${prompt}"><span class="floating-label">AI GENERATED · SAMPLE</span><span class="circle-arrow" aria-hidden="true">↗</span></button><figcaption><span class="kicker">${cat}</span><h2>${title}</h2><p>${lead}<br>${desc}</p><span class="subtle">${prompt}</span></figcaption></figure>`).join('')}</div><div class="bottom-note"><p>한 장의 이미지에서, 움직이는 이야기로.</p><a href="video.html">영상 작업 보러 가기 &nbsp; ↗</a></div>`;
const video=heading(3,'Stories in','<br>motion.','정지된 이미지 너머, 시간과 움직임으로.<br>짧은 장면에 담은 이야기와 영상 제작 노트입니다.')+`<div class="hero-meta"><span class="pill">MOTION STUDIES</span><span class="subtle">영상 기획 샘플 · 실제 영상은 준비 중입니다</span></div><section class="cinema"><div class="screen"><img class="art" src="assets/pink-dune.png" alt="분홍빛 천과 사구를 활용한 영상 콘셉트 이미지"><span class="floating-label">01 / CONCEPT FILM</span><div class="screen-title">Between<br>light & silence.</div></div><div class="video-info"><div><h2>빛과 고요 사이</h2><p>30초 콘셉트 필름 기획 · AI 영상 · 샘플</p></div><button class="play-button" data-story="film-1">기획 노트 보기 &nbsp; ↗</button></div></section><div class="section-top"><h2>On the storyboard <sup>02</sup></h2><span class="subtle">다음 장면을 준비하며</span></div><div class="video-grid"><article class="video-card"><img src="assets/green-glasshouse.png" alt="미래 정원 영상의 콘셉트 프레임"><div><span class="kicker">02 / BRAND FILM · 샘플</span><h3>내일의 정원</h3><p>도시 속 작은 초록 공간을 소개하는 15초 브랜드 영상 기획.</p><a class="read" href="#film-2" data-story="film-2">스토리보드 보기 <b>↗</b></a></div></article><article class="video-card"><img src="assets/blue-sculpture.png" alt="블루 조형물을 활용한 모션 스터디 콘셉트"><div><span class="kicker">03 / MOTION STUDY · 샘플</span><h3>형태의 가능성</h3><p>고정된 카메라 안에서 빛과 그림자의 작은 변화를 관찰하는 10초 영상 기획.</p><a class="read" href="#film-3" data-story="film-3">스토리보드 보기 <b>↗</b></a></div></article></div>`+[['film-1','빛과 고요 사이','00–10초: 넓은 사구를 고정된 카메라로 담습니다.','10–23초: 반투명 천이 약한 바람에 천천히 움직입니다. 형태 변형과 갑작스러운 움직임은 제한합니다.','23–30초: 같은 구도를 유지하며 빛이 천천히 잦아듭니다.'],['film-2','내일의 정원','00–05초: 유리 온실의 전경을 보여 줍니다.','05–10초: 잎에 맺힌 빛과 유리의 질감을 가까이 담습니다.','10–15초: 온실의 전경으로 돌아오며 이야기를 마무리합니다.'],['film-3','형태의 가능성','00–03초: 파란 조형물을 정면에서 고정 촬영합니다.','03–07초: 광원의 위치가 천천히 변하며 그림자가 이동합니다.','07–10초: 처음의 조명 상태로 돌아와 루프를 완성합니다.']].map(([id,title,...steps])=>`<article class="story" id="${id}"><span class="kicker">VIDEO PRODUCTION NOTE</span><h2>${title}</h2><p class="sample-note">임시 영상 기획안입니다. 현재 실제 재생 가능한 영상 파일은 등록되어 있지 않습니다.</p>${steps.map(p=>`<p>${p}</p>`).join('')}<p>제작 기준: 원본 구도 유지, 느린 움직임, 피사체 변형 최소화.</p></article>`).join('');
const final=heading(4,'From learning','<br>to creating.','배운 것을 연결해, 하나의 결과물로.<br>기획부터 제작까지 나의 최종 프로젝트를 소개합니다.')+`<div class="hero-meta"><span class="pill">FINAL PROJECT / 2026</span><span class="subtle">샘플 프로젝트 · 실제 제출물로 교체 예정</span></div><section class="project-banner"><img class="art" src="assets/green-glasshouse.png" alt="유리 온실과 식물이 있는 미래 정원 프로젝트 대표 이미지"><div class="project-title"><span class="pill">AI CREATIVE CAMPAIGN</span><h2>A greener<br>tomorrow.</h2><p>AI로 그려 보는, 조금 더 푸른 내일.</p></div></section><div class="project-facts"><div><span>PROJECT TYPE</span><strong>AI 콘텐츠 캠페인</strong></div><div><span>MY ROLE</span><strong>기획 · 콘텐츠 제작</strong></div><div><span>OUTPUT</span><strong>기사 · 이미지 · 영상 기획</strong></div><div><span>STATUS</span><strong>콘셉트 샘플</strong></div></div><section class="project-body"><h2>01 / Overview</h2><div><h3>먼 미래의 이야기보다,<br>오늘 상상할 수 있는 변화.</h3><p>‘도시의 작은 공간이 정원이 된다면?’이라는 질문에서 출발한 콘텐츠 캠페인입니다. 생성형 AI를 활용해 미래의 정원을 시각화하고, 그 공간에 담긴 이야기를 기사와 영상 기획으로 연결합니다.</p><p>이 페이지는 최종 프로젝트를 소개하기 위한 예시입니다. 프로젝트 주제, 역할, 제작 과정과 결과물을 실제 교육 산출물에 맞춰 교체할 수 있습니다.</p></div></section><div class="section-top" style="margin-top:10px"><h2>02 / The process</h2><span class="subtle">질문 → 실험 → 완성</span></div><section class="process"><article><span class="num">01</span><h3>질문을 발견하다</h3><p>전하고 싶은 메시지와 대상을 정하고, ‘도시 속 초록 공간’이라는 주제를 구체화합니다.</p><span class="pill">RESEARCH</span></article><article><span class="num">02</span><h3>장면을 실험하다</h3><p>색과 재질, 구도를 바꿔 가며 이미지를 제작하고 캠페인의 시각적 방향을 결정합니다.</p><span class="pill">EXPERIMENT</span></article><article><span class="num">03</span><h3>하나로 연결하다</h3><p>기사와 이미지, 영상 스토리보드를 같은 메시지로 묶어 최종 결과물을 구성합니다.</p><span class="pill">CREATE</span></article></section><div class="bottom-note"><p>이 프로젝트의 비주얼 실험을 살펴보세요.</p><a href="image.html">이미지 컬렉션 &nbsp; ↗</a></div>`;
const introduce=`<section class="intro-video-preview" aria-label="유튜브 영상 미리보기">
  <div class="intro-video-frame"><iframe src="https://www.youtube-nocookie.com/embed/tWx9MtcXMSc" title="유튜브 영상 미리보기" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
  <a class="intro-video-link" href="https://www.youtube.com/watch?v=tWx9MtcXMSc" target="_blank" rel="noopener noreferrer">YouTube에서 보기 ↗</a>
</section>
<div class="eyebrow">ABOUT ME / PROM RECORD</div>
<section class="about-hero" aria-labelledby="about-title">
  <div class="about-lead"><span class="pill">AI CONTENT CREATOR</span><h1 id="about-title">PROM<br><span>RECORD.</span></h1><p class="about-tagline">생각을 콘텐츠로,<br>배움을 나만의 기록으로.</p><p>안녕하세요. 생성형 AI로 아이디어를 구체화하고,<br>이미지와 영상, 디자인으로 이야기를 만드는 크리에이터입니다.</p><a class="read" href="article.html">작업 기록 살펴보기 <b aria-hidden="true">↗</b></a></div>
  <figure class="about-art"><img src="assets/blue-sculpture.png" alt="유연한 사고를 표현한 파란 조형물과 투명한 구체"><figcaption>EXPLORE. CREATE. RECORD.</figcaption></figure>
</section>
<section class="about-statement" aria-labelledby="about-me-title"><h2 id="about-me-title">저를 소개합니다.</h2><div><p class="about-opening">새로운 도구를 배우고,<br>그 배움을 실제 결과물로 연결합니다.</p><p>저는 생성형 AI 콘텐츠, AI 아트, 영상, 디자인, 교육자료와 서비스 기획을 중심으로 작업합니다. 떠오른 아이디어를 글로 정리하고, 이미지로 실험하고, 움직이는 장면으로 확장하는 과정에 관심이 있습니다.</p><p>이곳은 한국경제 AI 교육에서 배우고 만든 결과물을 모으는 개인 포트폴리오입니다. 완성된 작업뿐 아니라 질문과 실험의 과정도 차근차근 기록하려고 합니다.</p></div></section>
<section aria-labelledby="about-fields-title"><div class="section-top"><h2 id="about-fields-title">제가 만드는 것들</h2><span class="subtle">MY CREATIVE PRACTICE</span></div><div class="about-fields"><article><span class="kicker">01 / VISUAL</span><h3>AI 아트 & 디자인</h3><p>색과 구도, 재질을 실험하며 머릿속 이미지를 눈에 보이는 장면으로 만듭니다.</p><a class="read" href="image.html">이미지 작업 <b aria-hidden="true">↗</b></a></article><article><span class="kicker">02 / MOTION</span><h3>영상 & 스토리텔링</h3><p>이야기의 흐름을 설계하고, 장면과 움직임을 통해 메시지를 전달합니다.</p><a class="read" href="video.html">유튜브 바로가기 <b aria-hidden="true">↗</b></a></article><article><span class="kicker">03 / IDEAS</span><h3>교육자료 & 서비스 기획</h3><p>복잡한 내용을 이해하기 쉽게 정리하고, 아이디어를 활용할 수 있는 구조로 구체화합니다.</p><a class="read" href="final.html">프로젝트 보기 <b aria-hidden="true">↗</b></a></article></div></section>
<div class="favorite-channel"><a class="favorite-channel-button" href="https://www.youtube.com/@nowhospital">바로가기</a></div>
<section class="about-values" aria-labelledby="about-values-title"><span class="eyebrow">HOW I CREATE</span><h2 id="about-values-title">도구는 새롭게,<br>관점은 나답게.</h2><p>무엇을 전하고 싶은지 먼저 생각합니다.<br>작게 시도하고, 직접 살펴보고, 더 나은 표현으로 다듬습니다.<br>그 과정에서 발견한 것을 다음 작업의 출발점으로 삼습니다.</p></section>`;
for(const [name,content] of Object.entries({introduce,article,image:images,video,final}))fs.writeFileSync(`${name}.html`,shell(name,content));
fs.copyFileSync('article.html','index.html');
console.log('Created introduce.html, article.html, image.html, video.html, final.html, index.html');
